---
title: "Untitled"
author: "Peter Sullivan"
date: "5/2/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidyquant)
library(dplyr)
library(shiny)
```

# Stock App

Pick a stock and see the last four years of recorded adjusted prices. This data was obtained from Yahoo finance using the package tidyquant.

```{r APP, echo=FALSE}


stocks <- c("MSFT","GOOG","AAPL","AMZN","FB","MTNB","LUV","CSCO","GLMD","RIOT","MRNA","CO")


data <- tq_get(stocks, get = "stock.prices", from = Year_4_date)


ui <- fluidPage(
    titlePanel("Stock Prices"),
    sidebarLayout(
        sidebarPanel(
            selectInput("stock", "Stock Symbol:",
                        choices = unique(data$symbol)),
            hr(),
            helpText("Pick a Stock from the Predetermined List")
        ),
        #create a spot for the plot
        mainPanel(
            plotOutput("StockPlot")
        )
    )
)


server <- function(input, output){
    output$StockPlot <- renderPlot({
        data %>%
            filter(symbol == input$stock)%>%
            ggplot()+
            geom_line(aes(x = date, y = adjusted))
    })
}

# Run the application 
shinyApp(ui = ui, server = server)




```


